services:
  postgres_db:
    image: postgres:12.16
    container_name: postgresdb-dev
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "db"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  mongo_db:
    image: mongo:7.0.0
    container_name: mongodb-dev
    command:
      ["--replSet", "rs0", "--bind_ip_all"]
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/etc/mongo
      - ./.docker/mongo/rs-initiate.js:/docker-entrypoint-initdb.d/rs-initiate.js
      # - ./.docker/mongo/replica.key:/data/replica.key
